name: Remotely Triggered 1

on:
  repository_dispatch:
    types: [ my-event ]
    
  workflow_dispatch:
  
jobs:
  build:
    name: run-workflow
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: print trigger details
        run: |
          echo ${{ github.event_name }}
          echo ${{ github.event.client_payload.github.action }}
          echo ${{ github.event.client_payload.github.actor }}
          echo ${{ inputs.name }}
          echo ${{ TEST_ENV }}
          echo ${{ SERVICE }}
          
      - name: print only if repository dispatch
        if: ${{ !github.event.issue.pull_request && github.event.issue.number == 2 || github.event_name == 'repository_dispatch' }}
        run: |
          echo ${{ github.event_name }}
